---
title: qui3tly.cloud
favicon: https://cdn-icons-png.flaticon.com/512/2593/2593635.png
theme: dark
color: slate

layout:
  Master:
    style: row
    columns: 3
  Lady:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 4
  Management:
    style: row
    columns: 3

providers:
  docker:
    socket: /var/run/docker.sock
