---
# MASTER IT-TOOLS - Developer utilities
# Usage: ansible-playbook -i inventory/production.ini playbooks/07-it-tools.yml

- name: Deploy IT-Tools on Master
  hosts: master
  become: true
  become_user: "{{ admin_user }}"
  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all.yml"
    - "{{ playbook_dir }}/../../host_vars/master.yml"

  tasks:
    - name: Pull latest from GitHub
      ansible.builtin.git:
        repo: "https://github.com/quietly007/quietly.its.me.git"
        dest: "{{ ansible_env.HOME }}"
        version: main
        update: yes
        force: no
      when: not ansible_check_mode

    - name: Check compose file exists
      ansible.builtin.stat:
        path: "{{ compose_dir }}/it-tools/docker-compose.yaml"
      register: it_tools_compose

    - name: Fail if compose file missing
      ansible.builtin.fail:
        msg: "Compose file missing at {{ compose_dir }}/it-tools/docker-compose.yaml"
      when: not it_tools_compose.stat.exists

    - name: Start IT-Tools
      community.docker.docker_compose_v2:
        project_src: "{{ compose_dir }}/it-tools"
        state: present

    - name: Show status
      ansible.builtin.debug:
        msg: "IT-Tools deployed at https://tools.quietly.its.me"
